server:
  port: 8080

spring:
  application:
    name: grc

  profiles:
    active: dev

#  web:
#    resources:
#      static-locations: classpath:/static/

# admin pwd
device:
  admin-password: 1234